import test from "node:test";import assert from "node:assert/strict";
import {STAFF,SITES,LOCATIONS,WORLD,campaign,SAVE_KEY,levelFor} from "../src/data.js";
import {freshState,validateSave,acceptQuest,answerQuest,turnIn,finishCampaign,collect,loadState,saveState,circleBlocked,movePlayer} from "../src/state.js";
import {createWorld} from "../src/world.js";import {perspective,viewMatrix,rgb} from "../src/engine.js";
const world=createWorld();
test("All 35 requested offices, 19 stations and 9 landmarks exist",()=>{assert.equal(STAFF.length,35);assert.equal(SITES.length,19);assert.equal(LOCATIONS.length,63);assert.equal(new Set(LOCATIONS.map(s=>s.id)).size,63);assert.deepEqual(Object.fromEntries(["Executive","Senior","Academic","Corporate"].map(g=>[g,STAFF.filter(s=>s.group===g).length])),{Executive:4,Senior:7,Academic:11,Corporate:13});for(const s of STAFF){assert.ok(s.description.length>70);assert.equal(s.options.length,3);assert.ok(s.correct>=0&&s.correct<3);assert.ok(SITES[s.site]);}});
test("All projects have a complete, idempotent accept/solve/return loop",()=>{const state=freshState();for(const s of STAFF){assert.equal(turnIn(state,s.id),false);assert.equal(answerQuest(state,s.id,s.correct),false);assert.equal(acceptQuest(state,s.id),true);assert.equal(acceptQuest(state,s.id),false);assert.equal(answerQuest(state,s.id,(s.correct+1)%3),false);assert.equal(state.quests[s.id],"active");assert.equal(answerQuest(state,s.id,s.correct),true);assert.equal(state.quests[s.id],"ready");assert.equal(turnIn(state,s.id),true);assert.equal(turnIn(state,s.id),false);}assert.equal(state.xp,4200);assert.equal(state.credits,1225);assert.equal(campaign(state).ready,true);assert.equal(finishCampaign(state),true);assert.equal(finishCampaign(state),false);assert.equal(state.xp,4700);assert.equal(state.credits,1375);});
test("Campaign cannot finish early; minimum requirements are exact",()=>{const state=freshState();assert.equal(finishCampaign(state),false);const chosen=[STAFF[0],...STAFF.filter(s=>s.group==="Academic").slice(0,6),...STAFF.filter(s=>s.group==="Corporate").slice(0,3)];for(const s of chosen){acceptQuest(state,s.id);answerQuest(state,s.id,s.correct);turnIn(state,s.id);}assert.equal(campaign(state).ready,true);assert.equal(campaign(state).total,10);});
test("24 collectibles reward only once and survive serialization",()=>{const s=freshState();for(let i=0;i<24;i++){assert.equal(collect(s,i),true);assert.equal(collect(s,i),false);}assert.equal(collect(s,24),false);assert.equal(collect(s,-1),false);assert.equal(s.xp,720);assert.equal(levelFor(s.xp),3);assert.deepEqual(validateSave(JSON.parse(JSON.stringify(s))),s);});
test("Invalid saves fail safely; reward totals cannot be inflated by fields",()=>{assert.throws(()=>validateSave({version:2}));assert.throws(()=>validateSave(null));const s=validateSave({version:1,name:"<script>",xp:9e12,credits:999,position:{x:Infinity,z:0},quests:{invented:"done",pceo:"done"},collectibles:[0,0,-1,24,1],settings:{quality:99,sensitivity:100}});assert.equal(s.xp,180);assert.equal(s.credits,35);assert.equal(s.name,"script");assert.deepEqual(s.position,WORLD.spawn);assert.equal(s.settings.sensitivity,2.5);assert.equal(s.settings.quality,1);assert.equal(s.finished,false);});
test("Storage errors are recoverable and do not erase corrupt saves",()=>{const storage={getItem:()=>"invalid",setItem:()=>{throw Error();}};assert.ok(loadState(storage).error);assert.equal(saveState(storage,freshState()),false);let data;const good={getItem:()=>data,setItem:(k,v)=>{assert.equal(k,SAVE_KEY);data=v;}};assert.equal(saveState(good,freshState()),true);assert.equal(loadState(good).exists,true);});
test("Movement respects walls, sliding, high delta and world boundaries",()=>{const wall=[{x:0,z:0,w:1,d:10}],p={x:-4,z:0};movePlayer(p,20,0,wall);assert.ok(p.x<-.9);movePlayer(p,0,20,wall);assert.ok(p.z>10);movePlayer(p,1000,1000,[]);assert.ok(p.x<WORLD.max&&p.z<WORLD.max);assert.equal(circleBlocked(WORLD.spawn.x,WORLD.spawn.z,world.colliders),false);});
test("Geometry is finite, nonzero and contains all NPCs and collectibles",()=>{assert.equal(world.people.length,32);assert.equal(world.tokens.length,24);assert.ok(world.boxes.length>3000);for(const b of [...world.boxes,...world.octs]){for(const key of ["x","y","z","w","h","d"])assert.ok(Number.isFinite(b[key]));assert.ok(b.w>0&&b.h>0&&b.d>0);}assert.equal(world.person(0,0,"#ffffff",0).length,9);});
test("Every office, station and collectible is reachable on one continuous collision mesh",()=>{
// Flood fill at 2 game-unit resolution, with a full player-radius clearance.
const min=-340,max=340,step=2,n=(max-min)/step+1,blocked=new Uint8Array(n*n),seen=new Uint8Array(n*n),index=(x,z)=>Math.round((z-min)/step)*n+Math.round((x-min)/step);
for(const b of world.colliders){const x0=Math.max(0,Math.floor((b.x-b.w/2-.65-min)/step)),x1=Math.min(n-1,Math.ceil((b.x+b.w/2+.65-min)/step)),z0=Math.max(0,Math.floor((b.z-b.d/2-.65-min)/step)),z1=Math.min(n-1,Math.ceil((b.z+b.d/2+.65-min)/step));for(let iz=z0;iz<=z1;iz++)for(let ix=x0;ix<=x1;ix++)if(circleBlocked(min+ix*step,min+iz*step,[b]))blocked[iz*n+ix]=1;}
const start=index(WORLD.spawn.x,WORLD.spawn.z),queue=new Int32Array(n*n);let read=0,write=1;queue[0]=start;seen[start]=1;while(read<write){const p=queue[read++],x=p%n,z=Math.floor(p/n);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=z+dz;if(a<0||a>=n||b<0||b>=n)continue;const v=b*n+a;if(!blocked[v]&&!seen[v]){seen[v]=1;queue[write++]=v;}}}
for(const s of STAFF)assert.ok(seen[index(s.x+11,s.z+1)],`Office unreachable: ${s.office}`);for(const s of SITES)assert.ok(seen[index(s.x,s.z+13)],`Station unreachable: ${s.name}`);for(const t of world.tokens)assert.ok(seen[index(t.x,t.z)],`Prism unreachable: ${t.id}`);assert.ok(write>70000,`Connected walkable area: ${write}`);
});
test("Camera matrices have expected handedness and finite projections",()=>{assert.deepEqual(rgb("#ff0000"),[1,0,0]);const p=perspective(Math.PI/3,16/9,.1,1000);assert.ok([...p].every(Number.isFinite));const v=viewMatrix(0,0,0,0,0);assert.equal(v[0],1);assert.equal(v[5],1);assert.equal(v[10],1);});
